package abbos.uzeu.common;

import java.util.ArrayList;

/**
 * Bu klass matnni krilldan lotinga, lotindan krillga
 * o'tqazish uchun ishlatiladi.
 * <p>
 * Ishlatilishi
 * KLKconvertor convertor = new KLKconvertor();
 * String s = "OnlineKurs";
 * String t = convertor.LotinToKrill(s);
 */

public class KLKconvertor {
    private ArrayList<String> l1;
    private ArrayList<String> l2;
    private ArrayList<String> k1;
    private ArrayList<String> k2;

    public KLKconvertor() {
        l1 = new ArrayList<>();
        l2 = new ArrayList<>();
        k1 = new ArrayList<>();
        k2 = new ArrayList<>();
        //////**********Lotindan Krillga***********////////
        l1.add("CH");
        k1.add("Ч");
        l1.add("Ch");
        k1.add("Ч");
        l1.add("SH");
        k1.add("Ш");
        l1.add("Sh");
        k1.add("Ш");
        l1.add("SHA");
        k1.add("Щ");
        l1.add("Sha");
        k1.add("Щ");
        l1.add("YO");
        k1.add("Ё");
        l1.add("Yo");
        k1.add("Ё");
        l1.add("YU");
        k1.add("Ю");
        l1.add("Yu");
        k1.add("Ю");
        l1.add("YA");
        k1.add("Я");
        l1.add("Ya");
        k1.add("Я");
        l1.add("O'");
        k1.add("Ў");
        l1.add("O`");
        k1.add("Ў");
        l1.add("O’");
        k1.add("Ў");
        l1.add("G`");
        k1.add("Ғ");
        l1.add("G'");
        k1.add("Ғ");
        l1.add("G’");
        k1.add("Ғ");
        l1.add("ch");
        k1.add("ч");
        l1.add("sh");
        k1.add("ш");
        l1.add("yo");
        k1.add("ё");
        l1.add("yu");
        k1.add("ю");
        l1.add("ya");
        k1.add("я");
        l1.add("o'");
        k1.add("ў");
        l1.add("o’");
        k1.add("ў");
        l1.add("o`");
        k1.add("ў");
        l1.add("g`");
        k1.add("ғ");
        l1.add("g'");
        k1.add("ғ");
        l1.add("g’");
        k1.add("ғ");
        l1.add("a");
        k1.add("а");
        l1.add("b");
        k1.add("б");
        l1.add("d");
        k1.add("д");
        l1.add("e");
        k1.add("э");
        l1.add("f");
        k1.add("ф");
        l1.add("g");
        k1.add("г");
        l1.add("h");
        k1.add("ҳ");
        l1.add("i");
        k1.add("и");
        l1.add("j");
        k1.add("ж");
        l1.add("k");
        k1.add("к");
        l1.add("l");
        k1.add("л");
        l1.add("m");
        k1.add("м");
        l1.add("n");
        k1.add("н");
        l1.add("o");
        k1.add("о");
        l1.add("p");
        k1.add("п");
        l1.add("q");
        k1.add("қ");
        l1.add("r");
        k1.add("р");
        l1.add("s");
        k1.add("с");
        l1.add("t");
        k1.add("т");
        l1.add("u");
        k1.add("у");
        l1.add("x");
        k1.add("х");
        l1.add("y");
        k1.add("й");
        l1.add("v");
        k1.add("в");
        l1.add("z");
        k1.add("з");
        l1.add("'");
        k1.add("ъ");
        l1.add("`");
        k1.add("ъ");
        l1.add("’");
        k1.add("ъ");
        l1.add("A");
        k1.add("А");
        l1.add("B");
        k1.add("Б");
        l1.add("D");
        k1.add("Д");
        l1.add("E");
        k1.add("Э");
        l1.add("F");
        k1.add("Ф");
        l1.add("G");
        k1.add("Г");
        l1.add("H");
        k1.add("Ҳ");
        l1.add("I");
        k1.add("И");
        l1.add("J");
        k1.add("Ж");
        l1.add("K");
        k1.add("К");
        l1.add("L");
        k1.add("Л");
        l1.add("M");
        k1.add("М");
        l1.add("N");
        k1.add("Н");
        l1.add("O");
        k1.add("О");
        l1.add("P");
        k1.add("П");
        l1.add("Q");
        k1.add("Қ");
        l1.add("R");
        k1.add("Р");
        l1.add("S");
        k1.add("С");
        l1.add("T");
        k1.add("Т");
        l1.add("U");
        k1.add("У");
        l1.add("X");
        k1.add("Х");
        l1.add("Y");
        k1.add("Й");
        l1.add("V");
        k1.add("В");
        l1.add("Z");
        k1.add("З");
        //////**********Lotindan Krillga***********////////
        //////**********Krilldan Lotinga***********////////
        k2.add("ғ");
        l2.add("g'");
        k2.add("Ғ");
        l2.add("G'");
        k2.add("Ц");
        l2.add("S");
        k2.add("ц");
        l2.add("s");
        k2.add("Я");
        l2.add("Ya");
        k2.add("я");
        l2.add("ya");
        k2.add("Ё");
        l2.add("Yo");
        k2.add("ё");
        l2.add("yo");
        k2.add("Ю");
        l2.add("yu");
        k2.add("ю");
        l2.add("yu");
        k2.add("ъ");
        l2.add("'");
        k2.add("Ъ");
        l2.add("'");
        k2.add("ы");
        l2.add("");
        k2.add("Ы");
        l2.add("");
        k2.add("ь");
        l2.add("");
        k2.add("Ь");
        l2.add("");
        k2.add("а");
        l2.add("a");
        k2.add("б");
        l2.add("b");
        k2.add("д");
        l2.add("d");
        k2.add("э");
        l2.add("e");
        k2.add("ф");
        l2.add("f");
        k2.add("г");
        l2.add("g");
        k2.add("ҳ");
        l2.add("h");
        k2.add("и");
        l2.add("i");
        k2.add("ж");
        l2.add("j");
        k2.add("к");
        l2.add("k");
        k2.add("л");
        l2.add("l");
        k2.add("м");
        l2.add("m");
        k2.add("н");
        l2.add("n");
        k2.add("о");
        l2.add("o");
        k2.add("п");
        l2.add("p");
        k2.add("қ");
        l2.add("q");
        k2.add("р");
        l2.add("r");
        k2.add("с");
        l2.add("s");
        k2.add("т");
        l2.add("t");
        k2.add("у");
        l2.add("u");
        k2.add("й");
        l2.add("y");
        k2.add("х");
        l2.add("x");
        k2.add("в");
        l2.add("v");
        k2.add("з");
        l2.add("z");
        k2.add("ш");
        l2.add("sh");
        k2.add("щ");
        l2.add("sha");
        k2.add("ч");
        l2.add("ch");
        k2.add("ў");
        l2.add("o'");
        k2.add("А");
        l2.add("A");
        k2.add("Б");
        l2.add("B");
        k2.add("Д");
        l2.add("D");
        k2.add("Э");
        l2.add("E");
        k2.add("Ф");
        l2.add("F");
        k2.add("Г");
        l2.add("G");
        k2.add("Ҳ");
        l2.add("H");
        k2.add("И");
        l2.add("I");
        k2.add("Ж");
        l2.add("J");
        k2.add("К");
        l2.add("K");
        k2.add("Л");
        l2.add("L");
        k2.add("М");
        l2.add("M");
        k2.add("Н");
        l2.add("N");
        k2.add("О");
        l2.add("O");
        k2.add("П");
        l2.add("P");
        k2.add("Қ");
        l2.add("Q");
        k2.add("Р");
        l2.add("R");
        k2.add("С");
        l2.add("S");
        k2.add("Т");
        l2.add("T");
        k2.add("У");
        l2.add("U");
        k2.add("Й");
        l2.add("Y");
        k2.add("Х");
        l2.add("X");
        k2.add("В");
        l2.add("V");
        k2.add("З");
        l2.add("Z");
        k2.add("Ш");
        l2.add("Sh");
        k2.add("Щ");
        l2.add("Sha");
        k2.add("Ч");
        l2.add("Ch");
        k2.add("Ў");
        l2.add("O'");
        //////**********Krilldan Lotinga***********////////
    }

    public String LotinToKrill(String s) {
        for (int i = 0; i < l1.size(); i++)
            s = s.replace(l1.get(i), k1.get(i));
        return s;
    }

    public String KrillToLotin(String s) {
        for (int i = 0; i < k2.size(); i++)
            s = s.replace(k2.get(i), l2.get(i));
        return s;
    }
}